server:
  port: 8083
  servlet:
    context-path: /api-v1

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactiondb
      auto-index-creation: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      customer-service:
        url: http://localhost:8080
        readTimeout: 30000
      account-service:
        url: http://localhost:8081
      credit-service:
        url: http://localhost:8082